//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak2
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignments2
    {
        public assignments2()
        {
            this.groups = new HashSet<groups2>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> maxSubmisions { get; set; }
        public Nullable<int> groupSize { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int courseID { get; set; }
    
        public virtual courses2 courses { get; set; }
        public virtual ICollection<groups2> groups { get; set; }
    }
}
