//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak2
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses
    {
        public courses()
        {
            this.assignments = new HashSet<assignments>();
            this.studentCourses = new HashSet<studentCourses>();
            this.teacherCourses = new HashSet<teacherCourses>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<assignments> assignments { get; set; }
        public virtual ICollection<studentCourses> studentCourses { get; set; }
        public virtual ICollection<teacherCourses> teacherCourses { get; set; }
    }
}
