//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak2
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses2
    {
        public courses2()
        {
            this.assignments = new HashSet<assignments2>();
            this.studentCourses = new HashSet<studentCourses2>();
            this.teacherCourses = new HashSet<teacherCourses2>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<assignments2> assignments { get; set; }
        public virtual ICollection<studentCourses2> studentCourses { get; set; }
        public virtual ICollection<teacherCourses2> teacherCourses { get; set; }
    }
}
