//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VLN2_2016_H42Entities : DbContext
    {
        public VLN2_2016_H42Entities()
            : base("name=VLN2_2016_H42Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignmentParts> assignmentParts { get; set; }
        public virtual DbSet<assignments> assignments { get; set; }
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<studentCourses> studentCourses { get; set; }
        public virtual DbSet<SystemUsers> SystemUsers { get; set; }
        public virtual DbSet<teacherCourses> teacherCourses { get; set; }
        public virtual DbSet<userAssignmentStats> userAssignmentStats { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<userTypes> userTypes { get; set; }
        public virtual DbSet<userUploadedSolution> userUploadedSolution { get; set; }
    }
}
