//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak2
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTypes
    {
        public userTypes()
        {
            this.users = new HashSet<users>();
        }
    
        public int ID { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
