//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak2
{
    using System;
    using System.Collections.Generic;
    
    public partial class users2
    {
        public users2()
        {
            this.groups = new HashSet<groups2>();
            this.studentCourses = new HashSet<studentCourses2>();
            this.teacherCourses = new HashSet<teacherCourses2>();
            this.userAssignmentStats = new HashSet<userAssignmentStats2>();
            this.userUploadedSolution = new HashSet<userUploadedSolution2>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int userTypeID { get; set; }
    
        public virtual ICollection<groups2> groups { get; set; }
        public virtual ICollection<studentCourses2> studentCourses { get; set; }
        public virtual ICollection<teacherCourses2> teacherCourses { get; set; }
        public virtual ICollection<userAssignmentStats2> userAssignmentStats { get; set; }
        public virtual userTypes2 userTypes { get; set; }
        public virtual ICollection<userUploadedSolution2> userUploadedSolution { get; set; }
    }
}
