//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooshak2
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.groups = new HashSet<groups>();
            this.studentCourses = new HashSet<studentCourses>();
            this.teacherCourses = new HashSet<teacherCourses>();
            this.userAssignmentStats = new HashSet<userAssignmentStats>();
            this.userUploadedSolution = new HashSet<userUploadedSolution>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int userTypeID { get; set; }
    
        public virtual ICollection<groups> groups { get; set; }
        public virtual ICollection<studentCourses> studentCourses { get; set; }
        public virtual ICollection<teacherCourses> teacherCourses { get; set; }
        public virtual ICollection<userAssignmentStats> userAssignmentStats { get; set; }
        public virtual userTypes userTypes { get; set; }
        public virtual ICollection<userUploadedSolution> userUploadedSolution { get; set; }
    }
}
